# This file configures the build and redirect settings for Netlify.

[build]
  # The command to build your Vite project.
  command = "npm install && npm run build"
  # The directory where the built files are located.
  publish = "dist"

# This is the redirect rule for Single Page Applications (SPAs).
# It ensures that all paths are served by index.html, allowing React Router to work.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
